#!/bin/bash

if [ $# -ne 1 ]
then
    echo "usage: Ltypes filename" >&2
    exit 2
fi

FILE="$1"

#TMPFILE='mktemp "${FILE}.XXXXXX"' || exit 1
TMPFILE=${FILE}.`date "+%s"`
touch $TMPFILE || exit 1

if [ `basename ${FILE}` != "xenv_linux.h" ]
then
# Change all the Xilinx types to Linux types and put the result into a temp file
sed	\
	-e 's/XENV_USLEEP/udelay/g' \
	-e 's/XENV_MEM_FILL/memset/g' \
	-e 's/XENV_MEM_COPY/memcpy/g' \
	-e 's/Xuint8/u8/g' \
	-e 's/Xuint16/u16/g' \
	-e 's/Xuint32/u32/g' \
	-e 's/Xint8/s8/g' \
	-e 's/Xint16/s16/g' \
	-e 's/Xint32/s32/g' \
	-e 's/Xboolean/u32/g' \
	"${FILE}" > "${TMPFILE}"

# Removed for 9.2.0
#	-e 's/XTRUE/TRUE/g' \
#	-e 's/XFALSE/FALSE/g' \
#	-e 's/XNULL/NULL/g' \

# Removed for 10.1.2
#	-e 's/"xenv.h"/<asm\/delay.h>/g' \

# Overlay the original file with the temp file
mv "${TMPFILE}" "${FILE}"
fi

# Add GPL
sed 's/All rights reserved\./All rights reserved\. \
\*     This program is free software; you can redistribute it and\/or modify \
\*     it under the terms of the GNU General Public License as published by \
\*     the Free Software Foundation\; either version 2 of the License, or \(at \
\*     your option\) any later version\. \
\*\
\*     You should have received a copy of the GNU General Public License \
\*     along with this program; if not\, write to the Free Software \
\*     Foundation\, Inc\.\, 51 Franklin St\, Fifth Floor\, Boston\, \
\*     MA  02110-1301  USA/' \
"${FILE}" > "${TMPFILE}"

# Overlay the original file with the temp file
mv "${TMPFILE}" "${FILE}"

# Are we doing xbasic_types.h?
if [ "${FILE##*/}" = xbasic_types.h ]
then
    # Remember as you're reading this that we've already gone through the prior
    # sed script.  We need to do some other things to xbasic_types.h:
    #   1) Add ifndefs around TRUE and FALSE defines
    #   2) Remove definition of NULL as NULL
    #   3) Replace most of the primitive types section with a #include
    sed \
	-e '/u32 true/,/#define false/Ic\
#ifndef TRUE\
#define TRUE 1\
#endif\
#ifndef FALSE\
#define FALSE 0\
#endif' \
	-e '/#define[[:space:]][[:space:]]*NULL[[:space:]][[:space:]]*NULL/d' \
	-e '/typedef[[:space:]][[:space:]]*unsigned[[:space:]][[:space:]]*char[[:space:]][[:space:]]*u8/,/typedef[[:space:]][[:space:]]*unsigned[[:space:]][[:space:]]*long[[:space:]][[:space:]]*u32.*boolean/c\
#include <linux/types.h>' \
	"${FILE}" > "${TMPFILE}"

    mv "${TMPFILE}" "${FILE}"
fi

